---
- name: Install dependencies
  apt:
    name: rsyslog-gnutls

- name: Change local logging format
  replace:
    dest: /etc/rsyslog.conf
    regexp: '^\$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
    replace: '# $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
  when: rsyslog_local_iso8601
  notify: restart rsyslog

- name: Deploy rsyslog configs
  template:
    src: etc/rsyslog.d/template.conf.j2
    dest: "/etc/rsyslog.d/{{ config.name }}.conf"
    mode: 0644
  with_items: "{{ rsyslog_configs }}"
  loop_control:
    loop_var: config
    label: "{{ config.name }}"
  notify: restart rsyslog
