---
rsyslog_configs:
  - name: some-remote-host
    destinations:
      - some-remote-host.tld:514
    disk_queue: true
  - name: mutli-remote-hosts
    destinations:
      - some-remote-host.tld:514
      - other-remote-host.tld:514
  - name: nofqdn
    use_fqdn: false
    destinations:
      - some-remote-host.tld:514
